language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3.3
  - hhvm

branches:
  only:
    - master

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
  - ./bin/travis/before_script.sh

script:
  - mkdir -p build/logs
  - ./bin/travis/script.sh

after_script:
  - php vendor/bin/coveralls
